highlighter: pygments

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

paginate: 7
paginate_path: "page:num"
layout: post
permalink: /:categories/:title
excerpt_separator: "[-----]"

# mode: dev
mode: product
url: https://dlutfrank.github.io/
devurl: http://localhost:4000/
name: xing
title: xing | Another yet unique freak is showing a freakshow
description: "xing's personal weblog, on coding or such stuff"

my:
    displayName: xing
    realName: Wenxing 
    realName_cn: 文兴
    jobTitle: "Andorid Coder"
    contact:
        qq: 369388067
        email: dlut.xing@gmail.com
        github: http://www.github.com/dlutfrank
        pinterest: https://www.pinterest.com/miblah/
        tel: 15210819651
        address:
            country: China
            state: Hubei
            city: Wuhan
            distribute: Hongshan
            postcode: 450000
            cell: "XuefuJiayuan"
    skills:
        frontend: ["HTML | Markdown", "CSS | SASS", "JS | jQuery", "Bootstrap"]
        backend: ["PHP", "MySQL", "Redis", "Regex", "Laravel", "OSC"]
        tools: ["Sublime Text", "Git | Github", "Linux", "Jekyll | Liquid"]

collections:
    qqGroupGuide:
        output: true

defaults:
  - scope:
        path: ""
        type: "posts"
    values:
        excerpt: "{{ page.content }} | slice: 0 300"
  - scope:
        path: ""
        type: "qqGroupGuide"
    values:
        layout: markdownreader_bare